# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a1af8b7ec0384cb2eb8632dcce78098f70913044b184d6db590f0814de540cb277cce64abb171afb7d0e12dc8af50617561306a23f984024619c96cacbd836d

test:
  secret_key_base: a95f532fbafa116ba209d92817191e71eaee68dc130bb5be7b585258a50e619749c525af13b6d0fe0008ba9047c51a16b45358a5edd701b387c02cea573763c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
